# based on https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/bioconda_utils-conda_build_config.yaml
python:
  - 3.9.*  *_cpython
#   - 3.8.*  *_cpython
#   - 3.7.*  *_cpython
#   - 3.6.*  *_cpython
python_impl:
  - cpython
#   - cpython
#   - cpython
#   - cpython
numpy:
  - 1.19.*
#   - 1.17.*
#   - 1.17.*
#   - 1.17.*
