{% set version = "0.17.1" %}

package:
  name: gimmemotifs
  version: {{ version }}

source:
  url: https://github.com/vanheeringen-lab/gimmemotifs/releases/download/{{ version }}/gimmemotifs-{{ version }}.tar.gz
  sha256: 4d73d4b1df0ef765414dac952bf1d26609e74e97f9a2ee2d3d65a09078e1ad4c

build:
  number: 0
  skip: True  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - pybedtools
  run:
    - biofluff >=3.0.4
    - configparser
    - dinamo  # [not osx]
    - diskcache
    - feather-format
    - future
    - gadem
    - genomepy >=0.10.0
    - homer
#    - ipywidgets  # Necessary for progress bar in Jupyter notebook
    - iteround
    - jinja2
    - logomaker
    - loguru
    - matplotlib-base >=3.1.2
    - meme >=5.1.1
    - ncurses >=6.1
    - pandas
    - prosampler
    - pillow >=0.7.1.2
    - pyarrow >=0.16.0
    - pybedtools
    - python
    - python-xxhash
    - pyyaml >=3.10
    - qnorm >=0.5
    - scikit-learn >=0.23.2
    - scipy >=1.4.1
    - seaborn >=0.10.1
    - six
    - statsmodels
    - tqdm >=4.46.1
    - trawler
    - ucsc-bigbedtobed
    - weeder
    - xdg
    - xgboost >=1.0.2
    - xxmotif
          
test:
  imports:
    - gimmemotifs

  commands:
    - gimme --help

about:
  home: https://github.com/vanheeringen-lab/gimmemotifs
  license: MIT
  summary: Motif prediction pipeline and various motif-related tools

extra:
  recipe-maintainers:
    - simonvh
  identifiers:
    - biotools:gimmemotifs
