{% set version = "0.17.1" %}

package:
  name: gimmemotifs
  version: {{ version }}

source:
  url: https://github.com/vanheeringen-lab/gimmemotifs/releases/download/{{ version }}/gimmemotifs-{{ version }}.tar.gz
  sha256: 4d73d4b1df0ef765414dac952bf1d26609e74e97f9a2ee2d3d65a09078e1ad4c

build:
  number: 0
  skip: True  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - configparser
    - diskcache
    - feather-format
    - bioconda::genomepy >=0.11.1
    - ipywidgets                    # Necessary for progress bar in Jupyter notebook
    - conda-forge::iteround
    - jinja2
    - bioconda::logomaker
    - loguru
    - matplotlib-base >=3.1.2
    - numpy >= 1.6.0
    - pandas >=1.0.3, <=1.1.5  # 1.3.5/1.4.2 are bugged
    - pyarrow >=0.16.0
    - pybedtools >=0.9.0
    - pysam >=0.16
    - python >=3.8
    - python-xxhash
    - conda-forge::qnorm  >=0.8.1
    - scikit-learn >=0.23.2
    - scipy >=1.4.1
    - seaborn >=0.10.1
    - statsmodels
    - tqdm >=4.46.1
    - xdg
    - xgboost >=1.0.2
    - conda-forge::gcc              # Necessary to install motif discovery tools
    - dinamo >=1.0
    - gadem >=1.3.1
    - homer >=4.11
    - meme >=5.4.1
    - prosampler >=1.0
    - trawler >=2.0
    - weeder >=2.0
    - xxmotif >=1.6
    - yamda >=0.1.00e9c9d
          
test:
  imports:
    - gimmemotifs

  commands:
    - gimme --help

about:
  home: https://github.com/vanheeringen-lab/gimmemotifs
  license: MIT
  summary: Motif prediction pipeline and various motif-related tools

extra:
  recipe-maintainers:
    - simonvh
  identifiers:
    - biotools:gimmemotifs
