{% set version = "0.7" %}
{% set sha256 = "1ecc0c173f25c9d2550fbbea55f9a7fa3e840227bca965d2ee0f6d2ae6b99e79" %}

package:
  name: krakenuniq
  version: {{ version }}

source:
  url: https://github.com/fbreitwieser/krakenuniq/archive/v{{ version }}_1.tar.gz
  sha256: {{ sha256 }}
  patches:
    - krakenuniq.patch
    - krakenuniq2.patch

build:
  number: 1

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - perl
    - zlib
    - bzip2
  run:
    - kmer-jellyfish 1.*
    - perl
    - rsync
    - wget
    - tar
    - perl-libwww-perl
    - perl-lwp-protocol-https

test:
  commands:
    - krakenuniq --version
    - krakenuniq-build --version
    - krakenuniq-extract-reads --help 2>&1 | grep Usage
    - krakenuniq-filter --version
    - krakenuniq-mpa-report --version
    - krakenuniq-report --version
    - krakenuniq-translate --version
    - read_merger.pl 2>&1 | grep "must have exactly two filename arguments"
    - build_taxdb 2>&1 | grep "USAGE"

about:
  home: https://github.com/fbreitwieser/krakenuniq
  license: GPLv3
  license_file: LICENSE.GPL-3.0
  summary: Metagenomics classifier with unique k-mer counting for more specific results

extra:
  identifiers:
    - biotools:krakenhll
